### ISSUE TITLE
🎯 What can I work on ? (Rust SDK)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-rust#8]
### Simplify developer flow
- [ ] #9
- [ ] #10

### Add new and missing features - GENERAL
- [ ] Multilingual (180 languages are supported)
- [ ] Create users
- [ ] Check if users exist

### Add new and missing features - READ
- [ ] Product: you can retrieve information about products
- [ ] Product images (get product image by field, size and language, current fields are: Front, Ingredients, Nutrition, Packaging)
- [ ] Additives, Allergens, Environment impact, Ingredient analysis, Nutrient levels, Nutrition facts (incl. micro-nutrients)
- [ ] Language dependant fields (like ingredients, product name, packaging text)
- [ ] Eco-Score, Nutri-Score, NOVA groups
- [ ] Translated, high-level and customizable product information (Attributes)
- [ ] Product completion status
- [ ] Folksonomy Engine (custom properties for products)
- [ ] Open Food Facts Events (Gamification)

### Add new and missing features - PERSONALIZATION
- [ ] Recommended Daily Intakes
- [ ] Translated, high-level and customizable product information (Attributes)
- [ ] Autocompleting for the user inputs, by giving suggestions for (Labels, categories, ingredients, additives, traces ...)

### Add new and missing features - SEARCH
- [ ] search products by tags
- [ ] search products with / without additives
- [ ] search products with keywords
- [ ] Personalized search

### Add new and missing features - WRITE
- [ ] Save product to Open Food Facts
- [ ] Send images
- [ ] User comments and auth
- [ ] Anonymous photo upload
- [ ] Photo operations (rotate, crop, select, unselect with language awareness)

### Add new and missing features - ML
- [ ] Robotoff support
- [ ] Extract ingredients from ingredients image: User can extract the ingredients text if it is missing
- [ ] Get the OCR of the ingredients photo (for validation purposes)

## Roadmap - Add new and missing features
- [ ] List of new APIs to implement: https://github.com/openfoodfacts/api-documentation/issues
- [ ] New APIs: https://github.com/openfoodfacts/api-documentation/issues?q=is%3Aissue+is%3Aopen+label%3A%22new+api+to+document%22
- [ ] Existing APIs: https://github.com/openfoodfacts/api-documentation/
